# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdduser():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adduser(self):
    self.driver.get("http://192.168.109.134:81/login?redirect=%2Findex")
    self.driver.set_window_size(1395, 977)
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(3) .el-input__inner").send_keys("admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(3) .el-input__inner").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, ".is-active > .el-tooltip")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".is-opened .svg-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-menu--vertical:nth-child(10) > .el-menu > .nest-menu:nth-child(1) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-col > .el-button--primary > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-col > .el-button--primary > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-row:nth-child(1) > .el-col > .el-form-item .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-row:nth-child(1) > .el-col > .el-form-item .el-input__inner").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".el-row:nth-child(3) > .el-col:nth-child(1) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-row:nth-child(3) > .el-col:nth-child(1) .el-input__inner").send_keys("23124asd")
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-col > .el-button--primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-row:nth-child(1) > .el-col > .el-form-item .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-row:nth-child(1) > .el-col > .el-form-item .el-input__inner").send_keys("asd12")
    self.driver.find_element(By.CSS_SELECTOR, ".el-row:nth-child(3) > .el-col:nth-child(1) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-row:nth-child(3) > .el-col:nth-child(1) .el-input__inner").send_keys("asdxc")
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".app-main").click()
  
